# Generated by Django 5.1.2 on 2024-11-06 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_user_name_user_patronymic_user_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='DefaultFirstName', max_length=36, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
