# Generated by Django 5.1.2 on 2024-11-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_remove_user_name_user_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
