# Generated by Django 5.1.2 on 2024-11-14 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я\\s\\-]{3,25}$', 'Только буквы, пробелы и тире')]),
        ),
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я]{3,4}$', 'Только буквы')]),
        ),
    ]
