# Generated by Django 5.1.2 on 2024-11-17 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_plane_planemodel_seatclass_transportcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='code',
            field=models.CharField(default='AB1234', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='aisles_bus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='aisles_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='row_length_bus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)]),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='row_length_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)]),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_left_bus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_left_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_middle_bus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_middle_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_right_bus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_right_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
