# Generated by Django 5.1.2 on 2024-11-18 11:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_flight_code_alter_planemodel_aisles_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='row_length_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
