# Generated by Django 5.1.2 on 2024-11-18 11:23

import flight.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_alter_ticket_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_datetime',
            field=models.DateTimeField(default=flight.models.default_arrival_datetime),
        ),
        migrations.AlterField(
            model_name='flight',
            name='depart_datetime',
            field=models.DateTimeField(default=flight.models.default_depart_datetime),
        ),
    ]
