# Generated by Django 5.1.2 on 2024-11-18 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_alter_flight_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking_date',
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 0, 0)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='depart_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 0, 0)),
        ),
    ]
