# Generated by Django 5.1.2 on 2024-11-18 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0011_remove_ticket_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='plane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flight.plane'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.seatclass'),
        ),
    ]
