# Generated by Django 5.1.2 on 2024-11-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0013_alter_seat_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='ticket',
        ),
        migrations.AddField(
            model_name='seat',
            name='ticket',
            field=models.ManyToManyField(default=None, null=True, related_name='seats', to='flight.ticket'),
        ),
    ]
