# Generated by Django 5.1.2 on 2024-11-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_remove_seat_ticket_seat_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passengers',
            field=models.ManyToManyField(default=None, null=True, related_name='flight_tickets', to='flight.passenger'),
        ),
    ]
