# Generated by Django 5.1.2 on 2024-11-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0016_ticket_booking_date_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('муж', 'Мужской'), ('жен', 'Женский')], max_length=36, verbose_name='Пол'),
        ),
    ]
