# Generated by Django 5.1.2 on 2024-11-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0017_alter_passenger_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='ticket',
        ),
        migrations.AddField(
            model_name='seat',
            name='passenger',
            field=models.ManyToManyField(default=None, null=True, related_name='seats', to='flight.passenger'),
        ),
    ]
