# Generated by Django 5.1.2 on 2024-12-06 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0019_remove_seat_passenger_passenger_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='seat',
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='flight.seat'),
        ),
    ]
