# Generated by Django 5.1.2 on 2024-12-06 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0020_remove_passenger_seat_passenger_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я\\s\\-]{3,25}$', 'Только буквы, пробелы и дефисы')]),
        ),
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я]{3,4}$', 'Только буквы')]),
        ),
    ]
