# Generated by Django 5.1.2 on 2024-12-06 03:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0021_alter_place_city_alter_place_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я\\s\\-]{3,25}$', 'Только буквы, пробелы и дефисы')], verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я]{3,4}$', 'Только буквы')], verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='plane_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.planemodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='transport_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.transportcompany', verbose_name='Авиакомпания'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='aisles_bus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Проходы в Бизнес-классе'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='aisles_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Проходы в Эконом-классе'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='row_length_bus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)], verbose_name='Длина ряда в Бизнес-классе'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='row_length_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Длина ряда в Эконом-классе'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_left_bus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Ряды в левой части Бизнес-класса'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_left_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Ряды в левой части Эконом-класса'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_middle_bus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Ряды в середине Бизнес-класса'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_middle_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Ряды в середине Эконом-класса'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_right_bus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Ряды в правой части Бизнес-класса'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_right_eco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Ряды в правой части Эконом-класса'),
        ),
        migrations.AlterField(
            model_name='transportcompany',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default='00000000000', max_length=18, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Введите корректный номер телефона.')]),
        ),
    ]
