# Generated by Django 5.1.2 on 2024-12-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0022_alter_place_city_alter_place_code_alter_plane_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
