# Generated by Django 5.1.2 on 2024-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0023_passenger_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
