# Generated by Django 5.1.2 on 2024-12-20 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0024_ticket_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Пассажир', 'verbose_name_plural': 'Пассажиры'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='plane',
            options={'verbose_name': 'Самолёт', 'verbose_name_plural': 'Самолёты'},
        ),
        migrations.AlterModelOptions(
            name='planemodel',
            options={'verbose_name': 'Модель самолёта', 'verbose_name_plural': 'Модели самолётов'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='seatclass',
            options={'verbose_name': 'Класс обслуживания', 'verbose_name_plural': 'Классы обслуживания'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterModelOptions(
            name='transportcompany',
            options={'verbose_name': 'Авиакомпания', 'verbose_name_plural': 'Авиакомпании'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я\\s\\-]{3,25}$', 'Только буквы, пробелы и дефисы')], verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я]{3,4}$', 'Только буквы')], verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='aisles_bus',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Проходы в Бизнес-классе'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='aisles_eco',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Проходы в Эконом-классе'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_left_bus',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Ряды в левой части Бизнес-класса'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_left_eco',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Ряды в левой части Эконом-класса'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_middle_bus',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Ряды в середине Бизнес-класса'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_middle_eco',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Ряды в середине Эконом-класса'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_right_bus',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Ряды в правой части Бизнес-класса'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='rows_right_eco',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Ряды в правой части Эконом-класса'),
        ),
    ]
