# Generated by Django 5.1.2 on 2024-12-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0025_alter_flight_options_alter_passenger_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='name',
            field=models.CharField(max_length=36, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='name',
            field=models.CharField(max_length=36, unique=True, verbose_name='Название модели'),
        ),
    ]
