# Generated by Django 5.1.2 on 2024-12-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0026_alter_plane_name_alter_planemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportcompany',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название компании'),
        ),
    ]
