# Generated by Django 5.1.2 on 2024-12-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0028_alter_flight_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='business_seat_cost',
            field=models.FloatField(default=2000.0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='economy_seat_cost',
            field=models.FloatField(default=1000.0),
        ),
    ]
